version: '3.3'

services:
  
  client:
    build:
      context: ../../../../
      dockerfile: infra/deploy/frontend/dev/Dockerfile
    ports:
       - "8080:8080"
       - "80:80"
    container_name: client
    networks:
      - locatec

  database:
      image: mysql
      container_name: database
      restart: always
      ports:
        - '3306:3306'
      #command: --init-file /init.sql
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ~/apps/mysql:/var/lib/locatec6
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_HOST: '%'
        TIMEZONE: UTC

      networks:
        - locatec

  server:
    build: 
      context: ../../../../
      dockerfile: infra/deploy/backend/dev/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    container_name: server
    networks:
      - locatec
    depends_on:
      - database
networks:
  locatec: