{
 "title": "Productos creados por localizacion",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Leer producto por localizacion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "leer_localizacion_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leer producto por categoria",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "leer_categoria_producto_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "productos eliminados por categoria",
   "type": "piechart",
   "description": "Productos eliminados por categoria",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eliminar_categoria_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Productos eliminados por localizacion",
   "type": "bargauge",
   "description": "Productos eliminados dependiendo su localizacion",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eliminar_localizacion_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cambio status por localizacion",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cambio_status_localizacion_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cambio status por categoria",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cambio_status_categoria_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actualizar productos por localizacion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "actualizar_localizacion_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actualizar producto por categoria",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "actualizar_categoria_producto_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Productos creados por categoria",
   "type": "barchart",
   "description": "Productos creados en el sistema, separados por categoria",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 32 },
   "targets": [
    { "expr": "crear_categoria_producto_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Productos creados por localizacion",
   "type": "piechart",
   "description": "Productos creados en el sistema, separados por localizacion",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crear_localizacion_producto_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}